language: python
# For a list of available versions, run
#     aws s3 ls s3://travis-python-archives/binaries/ubuntu/14.04/x86_64/
#
# Python 3.7+ needs a newer version of openssl than is available in trusty,
# so these must run on a newer platform (and since travis doesn't yet have
# containers for xenial, those must use VMs).
# YAML magic from https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-401924248
.mixins:
- &xenial-mixin
  dist: xenial
  sudo: true

jobs:
  include:
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - <<: *xenial-mixin
      python: 3.7
# command to install dependencies
install:
  - python setup.py install
# command to run tests
script: python setup.py test
